// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using umfgcloud.programcaoiii.vendas.api.Contexto;

#nullable disable

namespace umfgcloud.programcaoiii.vendas.api.Migrations
{
    [DbContext(typeof(ContextoVenda))]
    [Migration("20251030005110_CriacaoInicialCompleta")]
    partial class CriacaoInicialCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("umfgcloud.programcaoiii.vendas.api.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("NR_CPF");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DS_ENDERECO");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IN_ATIVO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NM_CLIENTE");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("umfgcloud.programcaoiii.vendas.api.Entidades.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<Guid>("ID_PRODUTO")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ID_VENDA")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IN_ATIVO");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("QT_ITEM");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_TOTAL");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_ITEM");

                    b.HasKey("Id");

                    b.HasIndex("ID_PRODUTO");

                    b.HasIndex("ID_VENDA");

                    b.ToTable("ITEM_VENDA", (string)null);
                });

            modelBuilder.Entity("umfgcloud.programcaoiii.vendas.api.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DS_PRODUTO");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("CD_EAN");

                    b.Property<decimal>("Estoque")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("QT_ESTOQUE");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IN_ATIVO");

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_PRECO_COMPRA");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_PRECO_VENDA");

                    b.HasKey("Id");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("umfgcloud.programcaoiii.vendas.api.Entidades.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<Guid>("ID_CLIENTE")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ID_VENDEDOR")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IN_ATIVO");

                    b.HasKey("Id");

                    b.HasIndex("ID_CLIENTE");

                    b.HasIndex("ID_VENDEDOR");

                    b.ToTable("VENDA", (string)null);
                });

            modelBuilder.Entity("umfgcloud.programcaoiii.vendas.api.Entidades.Vendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IN_ATIVO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NM_VENDEDOR");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("VENDEDOR", (string)null);
                });

            modelBuilder.Entity("umfgcloud.programcaoiii.vendas.api.Entidades.ItemVenda", b =>
                {
                    b.HasOne("umfgcloud.programcaoiii.vendas.api.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ID_PRODUTO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("umfgcloud.programcaoiii.vendas.api.Entidades.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("ID_VENDA")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("umfgcloud.programcaoiii.vendas.api.Entidades.Venda", b =>
                {
                    b.HasOne("umfgcloud.programcaoiii.vendas.api.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ID_CLIENTE")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("umfgcloud.programcaoiii.vendas.api.Entidades.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("ID_VENDEDOR")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("umfgcloud.programcaoiii.vendas.api.Entidades.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
